spring.application.name=O2N
# C?ng ch?y API
server.port=8080
# C?u h�nh k?t n?i MySQL (C?ng m?c ??nh th??ng l� 3306)
spring.datasource.url=jdbc:mysql://localhost:3306/old2new_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=root123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# C?u h�nh Hibernate (T? ??ng sinh/c?p nh?t b?ng)
spring.jpa.hibernate.ddl-auto=none
#spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# ===============================
# C?U H�NH G?I EMAIL (QU�N M?T KH?U)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dinhtuanduy2007@gmail.com
spring.mail.password=bvdjcmzdudhcfxrw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
# --- CLOUDINARY CONFIG ---
cloudinary.cloud-name=dep3rejur
cloudinary.api-key=278838318157488
cloudinary.api-secret=dKKlLKAhLXum3cE_ZhJWB78lsyo
# --- REDIS CLOUD CONFIG ---
# 1. Endpoint (TCP)
spring.data.redis.host=liked-fawn-67223.upstash.io
# 2. Port
spring.data.redis.port=6379
spring.data.redis.username=default
# 3. Password ( M� Token)
spring.data.redis.password=gQAAAAAAAQaXAAIncDI2NTBiZDJlMDgzMzA0YmQ5YTI5NTFkMDYxYzcwZTVjZnAyNjcyMjM
# 4. B?t SSL (Upstash B?t bu?c ph?i c� d�ng n�y)
spring.data.redis.ssl.enabled=true
# N�ng gi?i h?n t?i file l�n 50MB ?? up ???c video
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
# Cấu hình API Giao Hàng Nhanh - Môi trường Thật
ghn.api.url=https://online-gateway.ghn.vn/shiip/public-api/v2/shipping-order/fee
ghn.api.token=792c575b-4074-11f1-a2f3-7a98e334d8cc
ghn.api.shop-id=6404262