spring.application.name=O2N

# C?ng ch?y API
server.port=8080

# C?u hình k?t n?i MySQL (C?ng m?c ??nh th??ng là 3306)
spring.datasource.url=jdbc:mysql://localhost:3306/old2new_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=17102007
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# C?u hình Hibernate (T? ??ng sinh/c?p nh?t b?ng)
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# ===============================
# C?U HÌNH G?I EMAIL (QUÊN M?T KH?U)
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dinhtuanduy2007@gmail.com
spring.mail.password=bvdjcmzdudhcfxrw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com

# --- CLOUDINARY CONFIG ---
cloudinary.cloud-name=dep3rejur
cloudinary.api-key=278838318157488
cloudinary.api-secret=dKKlLKAhLXum3cE_ZhJWB78lsyo